Add new name for rows and columns
GraphLabsSuite/Core.Lib pull request #15
Opened 2021-04-24 14:39 UTC by ayarabaeva

2021-04-25 09:48 UTC, AMusatova approved these changes

2021-04-26 14:28 UTC, svtz requested changes

2021-04-26 14:28 UTC, svtz commented on src/Matrix/MatrixRow.tsx
> +      }
Слушай, но это же адовая жесть. Если у нас ещё один булев флаг появится, у нас ещё х2 строк кода будет?
Надо свернуть всё в один блок `<div>` и использовать inline, см вот отсюда и ниже: https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator

Это замечание относится ко всем файлам а не только к этому

2021-04-26 14:39 UTC, svtz commented on src/Matrix/MatrixRow.tsx
> +      }
+ можно какие-то куски в отдельные методы вынести при необходимости (если например сложные условия выходят)

2021-04-26 15:10 UTC, ayarabaeva commented on src/Matrix/MatrixRow.tsx
> +      }
done

2021-04-26 15:40 UTC, svtz approved these changes

2021-04-26 15:40 UTC, merged